### PR TITLE
Implement GetLatestCommand & Character Upgrade

### PR DESCRIPTION
**Pull request by ArkanDash**
New command to get latest/current jp character banner and partial character upgrade

### CODE REVIEW

**Comment by suna-aquatope** [comment]
is it memorial lobby for hoshino tactical work fine?

**Comment by ArkanDash** [comment]
> is it memorial lobby for hoshino tactical work fine?

Works fine to me. Because there is two ID I'm taking the first id.

**Comment by suna-aquatope** [comment]
> > is it memorial lobby for hoshino tactical work fine?
> 
> Works fine to me. Because there is two ID I'm taking the first id. If you find an issue with it, let me know

ah i see, because before i got problem with thats memorial lobby,but now i make changes to read new exceltable.bytes.

**Comment by suna-aquatope** [comment]
> > > > is it memorial lobby for hoshino tactical work fine?
> > > 
> > > 
> > > Works fine to me. Because there is two ID I'm taking the first id. If you find an issue with it, let me know
> > 
> > 
> > ah i see, because before i got problem with thats memorial lobby when using someone code,but now i've make changes to read new exceltable.bytes.
> 
> New BD L2D Exclusive just drops I find other abydos member bd exclusive too, but all of them aren't available yet. you will get black screen instead
> 
> image

yeah,i think abydos became first academy with student have multiple L2D Memorial Lobby.

**Pull request closed without merging**
